=== dandreavh/Lenguaje-de-Marcas/T1_Introduccion-XML/U1_T2_DTD/Ejercicio5/DTDej5.dtd
<!ELEMENT discos (disco+)>
<!ELEMENT disco (titulo, interpretes, pistas)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT interpretes (interprete+)>
<!ELEMENT interprete (nombre, apellidos, rol?)>
<!ELEMENT pistas (pista+)>
<!ELEMENT pista (numero, cancion, duracion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT rol (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT cancion (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>

=== dandreavh/Lenguaje-de-Marcas/T1_Introduccion-XML/U1_T2_DTD/Ejercicio5/Ej5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE discos SYSTEM "DTDej5.dtd">

<discos>
    <disco>
        <titulo>The Rolling Stones</titulo>
        <interpretes>
            <interprete>
                <nombre>Mick</nombre>
                <apellidos>Jagger</apellidos>
                <rol>cantante</rol>
            </interprete>
            <interprete>
                <nombre>Keith</nombre>
                <apellidos>Richards</apellidos>
                <rol>guitarrista</rol>
            </interprete>
            <interprete>
                <nombre>Brian</nombre>
                <apellidos>Jones</apellidos>
            </interprete>
        </interpretes>
        <pistas>
            <pista>
                <numero>1</numero>
                <cancion>Route 66</cancion>
                <duracion>2:57</duracion>
            </pista>
            <pista>
                <numero>2</numero>
                <cancion>Tell Me (You're Coming Back)</cancion>
                <duracion>2:47</duracion>
            </pista>
        </pistas>
    </disco>
    <disco>
        <titulo>30</titulo>
        <interpretes>
            <interprete>
                <nombre>Adele</nombre>
                <apellidos>Blue</apellidos>
            </interprete>
        </interpretes>
        <pistas>
            <pista>
                <numero>1</numero>
                <cancion>Easy On Me</cancion>
                <duracion>3:32</duracion>
            </pista>
        </pistas>
    </disco>
</discos>
