=== dandreavh/Lenguaje-de-Marcas/T1_Introduccion-XML/U1_T3_XSD-DTD/Ej5/ej5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="libros">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="codigo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[TPNH]\d{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="categoria">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Teatro"/>
                                        <xs:enumeration value="PoesÃ­a"/>
                                        <xs:enumeration value="Novela"/>
                                        <xs:enumeration value="Historia"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="titulo" type="xs:string" />
                            <xs:element name="autores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="autor" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"/>
                                                    <xs:element name="apellidos" type="xs:string"/>
                                                    <xs:element name="pseudonimo" type="xs:string" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="num_paginas" type="xs:integer" />
                            <xs:element name="anio_publicacion" type="xs:gYear" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dandreavh/Lenguaje-de-Marcas/T1_Introduccion-XML/U1_T3_XSD-DTD/Ej5/ej5.xml
<?xml version="1.0" encoding="UTF-8"?>
<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ej5.xsd">
    <libro>
        <codigo>N555</codigo>
        <categoria>Novela</categoria>
        <titulo>El árbol de la ciencia</titulo>
        <autores>
            <autor>
                <nombre>Pío</nombre>
                <apellidos>Baroja</apellidos>
                <pseudonimo>Pío Quinto</pseudonimo>
            </autor>
        </autores>
        <num_paginas>272</num_paginas>
        <anio_publicacion>1911</anio_publicacion>
    </libro>
    <libro>
        <codigo>T222</codigo>
        <categoria>Teatro</categoria>
        <titulo>Historia de una escalera</titulo>
        <autores>
            <autor>
                <nombre>Antonio</nombre>
                <apellidos>Buero Vallejo</apellidos>
            </autor>
        </autores>
        <num_paginas>160</num_paginas>
        <anio_publicacion>1949</anio_publicacion>
    </libro>
</libros>
