=== dandreavh/Lenguaje-de-Marcas/T1_Introduccion-XML/U1_T2_XSD/MarcadoresXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault ="qualified" >
    <xs:element name="bookmarks">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="page" maxOccurs="unbounded"/>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="description" type="xs:string" />
                            <xs:element name="url" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dandreavh/Lenguaje-de-Marcas/T1_Introduccion-XML/U1_T2_XSD/Marcadores.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookmarks
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="MarcadoresXSD.xsd">
    <page>
        <name>IESAlixar</name>
        <description>Our High School</description>
        <url>http://www.iesalixar.org</url>
    </page>
    <page>
        <name>Wikipedia</name>
        <description>The free enclyclopedia</description>
        <url>http://www.wikipedia.org</url>
    </page>
    <page>
        <name>W3C</name>
        <description>World Wide Web Consortium</description>
        <url>http://www.w3c.org</url>
    </page>
</bookmarks>
